Add xvfb-run to test run with exit code interpretation

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -18,18 +18,27 @@ variables:
   stage: test
   <<: *unity_before_script
   script: |
+    xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
     /opt/Unity/Editor/Unity \
-      -quit \
       -projectPath $(pwd) \
       -batchmode \
       -force-free \
-      -nographics \
       -runTests \
       -logFile \
       -testResults $(pwd)/$TEST_PLATFORM-results.xml \
       -testPlatform $TEST_PLATFORM
-    ls ./$TEST_PLATFORM-results.xml
+    UNITY_EXIT_CODE=$?
+    if [ $UNITY_EXIT_CODE -eq 0 ]; then
+      echo "Run succeeded, no failures occurred"
+    else if [ $UNITY_EXIT_CODE -eq 2 ]; then
+      echo "Run succeeded, some tests failed"
+    else if [ $UNITY_EXIT_CODE -eq 3 ]; then
+      echo "Run failure (other failure)"
+    else
+      echo "Unexpected exit code $UNITY_EXIT_CODE"
+    fi
     cat ./$TEST_PLATFORM-results.xml | grep test-run | grep Passed
+    exit $UNITY_TEST_EXIT_CODE
   artifacts:
     paths:
       - ./$TEST_PLATFORM-results.xml
@@ -51,7 +60,7 @@ test-playmode:
     echo "Building for $BUILD_TARGET"
     export BUILD_PATH=./Builds/$BUILD_TARGET/
     mkdir -p $BUILD_PATH
-    xvfb-run --server-args="-screen 0 1024x768x24" \
+    xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
       /opt/Unity/Editor/Unity \
       -projectPath $(pwd) \
       -quit \
@@ -69,6 +78,7 @@ test-playmode:
   artifacts:
     paths:
       - ./Builds/
+#uncomment following lines if you'd like to build only on master branch
 #   only:
 #     - master
 
@@ -77,16 +87,16 @@ build-StandaloneLinux64:
   variables:
     BUILD_TARGET: StandaloneLinux64
 
-# todo: use me for > 2017.2
-# build-StandaloneOSX:
-#   <<: *build
-#   variables:
-#     BUILD_TARGET: StandaloneOSX
-
-build-StandaloneOSXUniversal:
+build-StandaloneOSX:
   <<: *build
   variables:
-    BUILD_TARGET: StandaloneOSXUniversal
+    BUILD_TARGET: StandaloneOSX
+
+#For versions < 2017.2:
+# build-StandaloneOSXUniversal:
+#   <<: *build
+#   variables:
+#     BUILD_TARGET: StandaloneOSXUniversal
 
 build-StandaloneWindows64:
   <<: *build
